/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "程序猿日记",
  "description": "记录个人在编程世界中的点滴、心情和思考。",
  "base": "/docs/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/docs/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "程序猿日记"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "专注于Java编程技术的研究和分享"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.jpg",
        "heroText": "程序猿日记",
        "tagline": "Java之光",
        "actionText": "快速上手 →",
        "actionLink": "/my/my",
        "features": [
          {
            "title": "程序人生",
            "details": "分享程序员的生活态度、职业发展和技术探索。"
          },
          {
            "title": "Java探索者",
            "details": "专注于Java编程技术的研究和分享。"
          },
          {
            "title": "编程智慧",
            "details": "分享编程技巧、解决问题的思路和方法。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2023-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-4a244471",
      "path": "/"
    },
    {
      "title": "后端技术栈",
      "frontmatter": {},
      "regularPath": "/blog/backend/",
      "relativePath": "blog/backend/README.md",
      "key": "v-72db4227",
      "path": "/blog/backend/",
      "headers": [
        {
          "level": 2,
          "title": "Java",
          "slug": "java"
        },
        {
          "level": 2,
          "title": "MySQL",
          "slug": "mysql"
        },
        {
          "level": 2,
          "title": "SpringBoot",
          "slug": "springboot"
        },
        {
          "level": 2,
          "title": "SpringCloud",
          "slug": "springcloud"
        },
        {
          "level": 2,
          "title": "Redis",
          "slug": "redis"
        }
      ]
    },
    {
      "title": "计算机基础",
      "frontmatter": {
        "title": "计算机基础"
      },
      "regularPath": "/blog/basic/",
      "relativePath": "blog/basic/README.md",
      "key": "v-f48866b2",
      "path": "/blog/basic/",
      "headers": [
        {
          "level": 2,
          "title": "1.计算机组成原理",
          "slug": "_1-计算机组成原理"
        },
        {
          "level": 2,
          "title": "2.操作系统",
          "slug": "_2-操作系统"
        },
        {
          "level": 2,
          "title": "3.计算机网络",
          "slug": "_3-计算机网络"
        },
        {
          "level": 2,
          "title": "4.数据结构与算法",
          "slug": "_4-数据结构与算法"
        }
      ]
    },
    {
      "title": "计算机网络",
      "frontmatter": {
        "title": "计算机网络"
      },
      "regularPath": "/blog/basic/network/",
      "relativePath": "blog/basic/network/README.md",
      "key": "v-414ff98c",
      "path": "/blog/basic/network/",
      "headers": [
        {
          "level": 2,
          "title": "1.http",
          "slug": "_1-http"
        },
        {
          "level": 2,
          "title": "2.TCP/IP",
          "slug": "_2-tcp-ip"
        },
        {
          "level": 2,
          "title": "3.万维网",
          "slug": "_3-万维网"
        },
        {
          "level": 2,
          "title": "4.通信 你好",
          "slug": "_4-通信-你好"
        }
      ]
    },
    {
      "title": "Java",
      "frontmatter": {
        "title": "Java"
      },
      "regularPath": "/blog/backend/java.html",
      "relativePath": "blog/backend/java.md",
      "key": "v-632e0f64",
      "path": "/blog/backend/java.html",
      "headers": [
        {
          "level": 2,
          "title": "java",
          "slug": "java-2"
        },
        {
          "level": 3,
          "title": "java",
          "slug": "java-3"
        }
      ]
    },
    {
      "title": "前端技术栈",
      "frontmatter": {},
      "regularPath": "/blog/fontend/",
      "relativePath": "blog/fontend/README.md",
      "key": "v-b5d025b2",
      "path": "/blog/fontend/",
      "headers": [
        {
          "level": 2,
          "title": "前端三剑客",
          "slug": "前端三剑客"
        },
        {
          "level": 3,
          "title": "HTML",
          "slug": "html"
        },
        {
          "level": 3,
          "title": "CSS",
          "slug": "css"
        },
        {
          "level": 3,
          "title": "JavaScript",
          "slug": "javascript"
        },
        {
          "level": 2,
          "title": "BootStrap",
          "slug": "bootstrap"
        },
        {
          "level": 2,
          "title": "Vue",
          "slug": "vue"
        },
        {
          "level": 2,
          "title": "React",
          "slug": "react"
        },
        {
          "level": 2,
          "title": "TypeScript",
          "slug": "typescript"
        }
      ]
    },
    {
      "title": "HTML",
      "frontmatter": {
        "title": "HTML"
      },
      "regularPath": "/blog/fontend/html.html",
      "relativePath": "blog/fontend/html.md",
      "key": "v-5f2d7a78",
      "path": "/blog/fontend/html.html",
      "headers": [
        {
          "level": 2,
          "title": "HTML基础知识",
          "slug": "html基础知识"
        },
        {
          "level": 3,
          "title": "1. 标签",
          "slug": "_1-标签"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        }
      ]
    },
    {
      "title": "学习JavaScript",
      "frontmatter": {
        "0": "t",
        "1": "i",
        "2": "t",
        "3": "l",
        "4": "e",
        "5": ":",
        "6": "J",
        "7": "a",
        "8": "v",
        "9": "a",
        "10": "S",
        "11": "c",
        "12": "r",
        "13": "i",
        "14": "p",
        "15": "t"
      },
      "regularPath": "/blog/fontend/javascript.html",
      "relativePath": "blog/fontend/javascript.md",
      "key": "v-3f42e2c4",
      "path": "/blog/fontend/javascript.html"
    },
    {
      "title": "我的",
      "frontmatter": {},
      "regularPath": "/my/my.html",
      "relativePath": "my/my.md",
      "key": "v-444f7dd2",
      "path": "/my/my.html",
      "headers": [
        {
          "level": 2,
          "title": "我的",
          "slug": "我的"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/icon.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "计算机",
        "link": "/blog/basic/"
      },
      {
        "text": "前端",
        "link": "/blog/fontend/"
      },
      {
        "text": "后端",
        "link": "/blog/backend/"
      },
      {
        "text": "我的",
        "link": "/my/my"
      }
    ],
    "sidebar": {
      "/blog/basic/": [
        "",
        "network/"
      ],
      "/blog/fontend/": [
        "",
        "html",
        [
          "javascript",
          "Javascript"
        ]
      ],
      "/blog/backend/": [
        "",
        [
          "java",
          "Java"
        ]
      ]
    },
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "更新时间"
  }
}